upstream nextjs {
    server nextjs:3000;
}

upstream api {
    server api:8000;
}

server {
    listen 80;
    server_name sync-walk.sbs;

    location / {
        return 301 https://$host$request_uri;
    }
}
